### ISSUE TITLE
Support exporting metrics to a prometheus pushgateway

### ISSUE THREAD

**Issue by SoerenSilkjaer** [larscheid-schmitzhermes/keycloak-monitoring-prometheus#13]
I generally find using pushgateway an easy method to export metrics to prometheus.

**Comment by tobilarscheid** [comment]
Hi @sorenvalentinjp, thanks for your suggestion! From my understanding, pushgateway is made for cases where you can’t use regular scraping - so I don’t really see the advantage here. Actually, the pushgateway documentation seems to agree:
> The Prometheus Pushgateway exists to allow ephemeral and batch jobs to expose their metrics to Prometheus. 

But happy to discuss your use case!

**Comment by SoerenSilkjaer** [comment]
Hi @tobilarscheid 
I see your point. 
How do you scrape the metrics files from prometheus? I am used to running services in docker in docker orchestration platforms, where I expose a /metrics endpoint, and let service discovery register all the targets in prometheus scraper.

Thanks.

**Comment by tobilarscheid** [comment]
The metrics file is compatible with [`prometheus-filesystem-exporter`](https://github.com/larscheid-schmitzhermes/prometheus-filesystem-exporter) - which is build with keycloak running in docker in mind. Check it out!

If you don't like that file based approach, I also recommend checking out [`keycloak-metrics-spi`](https://github.com/aerogear/keycloak-metrics-spi). I haven't tried it myself, but it looks pretty good!
