### ISSUE TITLE
confusion around env variable naming. two different?

### ISSUE THREAD

**Issue by devdavidkarlsson** [larscheid-schmitzhermes/keycloak-monitoring-prometheus#5]
KEYCLOAK_PROMETHEUS_EVENTS_DIR in [MonitoringEventListenerProviderFactory](https://github.com/larscheid-schmitzhermes/keycloak-monitoring-prometheus/blob/94b6f9ccb42940d5a4a1074ef0aa97741da8189e/src/main/java/com/larscheidschmitzhermes/keycloak/events/MonitoringEventListenerProviderFactory.java) but it is called EVENTS_DIRECTORY in the Dockerfile in the conditional property setting.

Why is this?

Also: is it supposed to be a relative path, in that case relative to what?

**Comment by tobilarscheid** [comment]
‘KEYCLOAK_PROMETHEUS_EVENTS_DIR’ is just for the case that you can not influence keycloaks standalone.xml - see https://github.com/larscheid-schmitzhermes/keycloak-monitoring-prometheus#configuring-using-an-environment-variable

‘EVENTS_DIRECTORY’ is only valid in the scope of the sample dockerfile and has no meaning outside of it.

Relative path: no, always absolute!
